/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as SearchRouteImport } from './routes/search'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as MembersSlugRouteImport } from './routes/members/$slug'
import { Route as MembersArchivedRouteImport } from './routes/members/archived'
import { Route as MembersContributorsRouteImport } from './routes/members/contributors'
import { Route as VideosIndexRouteImport } from './routes/videos/index'
import { Route as VideosSlugRouteImport } from './routes/videos/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersSlugRoute = MembersSlugRouteImport.update({
  id: '/members/$slug',
  path: '/members/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersArchivedRoute = MembersArchivedRouteImport.update({
  id: '/members/archived',
  path: '/members/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersContributorsRoute = MembersContributorsRouteImport.update({
  id: '/members/contributors',
  path: '/members/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosSlugRoute = VideosSlugRouteImport.update({
  id: '/videos/$slug',
  path: '/videos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRoute
  '/search': typeof SearchRoute
  '/events/$slug': typeof EventsSlugRoute
  '/members/$slug': typeof MembersSlugRoute
  '/members/archived': typeof MembersArchivedRoute
  '/members/contributors': typeof MembersContributorsRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/events/': typeof EventsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRoute
  '/search': typeof SearchRoute
  '/events/$slug': typeof EventsSlugRoute
  '/members/$slug': typeof MembersSlugRoute
  '/members/archived': typeof MembersArchivedRoute
  '/members/contributors': typeof MembersContributorsRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/events': typeof EventsIndexRoute
  '/members': typeof MembersIndexRoute
  '/videos': typeof VideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/courses': typeof CoursesRoute
  '/search': typeof SearchRoute
  '/events/$slug': typeof EventsSlugRoute
  '/members/$slug': typeof MembersSlugRoute
  '/members/archived': typeof MembersArchivedRoute
  '/members/contributors': typeof MembersContributorsRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/events/': typeof EventsIndexRoute
  '/members/': typeof MembersIndexRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/courses'
    | '/search'
    | '/events/$slug'
    | '/members/$slug'
    | '/members/archived'
    | '/members/contributors'
    | '/videos/$slug'
    | '/events/'
    | '/members/'
    | '/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/courses'
    | '/search'
    | '/events/$slug'
    | '/members/$slug'
    | '/members/archived'
    | '/members/contributors'
    | '/videos/$slug'
    | '/events'
    | '/members'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/courses'
    | '/search'
    | '/events/$slug'
    | '/members/$slug'
    | '/members/archived'
    | '/members/contributors'
    | '/videos/$slug'
    | '/events/'
    | '/members/'
    | '/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoursesRoute: typeof CoursesRoute
  SearchRoute: typeof SearchRoute
  EventsSlugRoute: typeof EventsSlugRoute
  MembersSlugRoute: typeof MembersSlugRoute
  MembersArchivedRoute: typeof MembersArchivedRoute
  MembersContributorsRoute: typeof MembersContributorsRoute
  VideosSlugRoute: typeof VideosSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$slug': {
      id: '/members/$slug'
      path: '/members/$slug'
      fullPath: '/members/$slug'
      preLoaderRoute: typeof MembersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/archived': {
      id: '/members/archived'
      path: '/members/archived'
      fullPath: '/members/archived'
      preLoaderRoute: typeof MembersArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/contributors': {
      id: '/members/contributors'
      path: '/members/contributors'
      fullPath: '/members/contributors'
      preLoaderRoute: typeof MembersContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$slug': {
      id: '/videos/$slug'
      path: '/videos/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof VideosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoursesRoute: CoursesRoute,
  SearchRoute: SearchRoute,
  EventsSlugRoute: EventsSlugRoute,
  MembersSlugRoute: MembersSlugRoute,
  MembersArchivedRoute: MembersArchivedRoute,
  MembersContributorsRoute: MembersContributorsRoute,
  VideosSlugRoute: VideosSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  VideosIndexRoute: VideosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
